<?php

return [
    'artists_are_sortable' => false,
    'artists_have_custom_bg' => true,
    'artists_sortable_dropdown' => false,
    'custom_artist_label' => '',
    'custom_artists_label' => '',
    'custom_is_artist_portfolio_image_label' => '',
    'custom_overview_categories_label' => '',
    'custom_show_in_overview_label' => '',
    'custom_slideshow_label' => '',
    'custom_slideshows_label' => '',
    'custom_visible_in_artist_overview_label' => '',
    'custom_work_label' => '',
    'custom_works_label' => '',
    'db_prefix' => '',
    'has_break_after_in_overviews' => false,
    'has_artist_category' => false,
    'has_category_slideshows' => true,
    'has_custom_portfolio_image' => true,
    'has_projects_zip_upload' => false,
    'has_quick_upload' => true,
    'has_represents_artist_in_discipline_category'  => true,
    'has_show_in_overview_category'  => true,
    'has_show_title' => false,
    'has_starts_right' => false,
    'has_title_position' => false,
    'has_visible_in_artist_overview' => true,
    'max_thumbnails' => 3,
    'number_of_portfolio_images' => 1,
    'projects_zip_starts_with_categories' => false,
    'slideshows_sortable_dropdown' => false,
    'slideshows_sortable' => true,
    'works_sortable_dropdown' => false,
    'media' => [
        'upload_only' => true,
    ],
    'break_sizes' => [
        'large' => 'large',
        'regular' => 'regular',
        'small' => 'small',
        'none' => 'none',
    ],
];
